# Generated by Django 2.1.5 on 2019-02-01 06:42

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('params', jsonfield.fields.JSONField()),
                ('skip_words', models.CharField(blank=True, max_length=200, verbose_name='Skip words')),
                ('task_id', models.CharField(blank=True, max_length=200, verbose_name='Task id')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobmonitorweb.Monitor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Param code')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='message_backends',
            field=models.ManyToManyField(blank=True, limit_choices_to={'code': 'message_backend'}, related_name='message_backend_monitors', to='jobmonitorweb.Param', verbose_name='Message backends'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_class',
            field=models.ForeignKey(limit_choices_to={'code': 'monitor_class'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_class_monitors', to='jobmonitorweb.Param'),
        ),
    ]
