# Generated by Django 2.1.5 on 2019-02-02 07:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobmonitorweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='schedule',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
